db.py

add utf-8 encoding when read file to support more language.

add multi-language support for file read

---

gpt_engineer/db.py

Ensure directory exists before attempting to write file in db.py
- fixes #85
- fixes #69
- fixes #45

Fix: Ensure Directory Exists Before File Write Operation in db.py

---

gpt_engineer/steps.py
identity/respec
identity/spec
identity/unit_tests
identity/use_qa

Generates a specification based on requirements and then self-evaluates that spec and fills in any uncertainties. Then generates unit-tests before writing the actual code.

Add steps for unit_tests and specification

---

.gitignore

added the .idea folder of jetbrains IDEs to the gitignore file, below vscode

added .idea folder of jetbrains IDEs to gitignore

---

tests/test_db.py

fixed the DB import on the test_db file

fixed the DB import in the pytest file

---

gpt_engineer/main.py
identity/generate
scripts/benchmark.py

fix docstring #150

---

gpt_engineer/ai.py
gpt_engineer/db.py
gpt_engineer/main.py
scripts/benchmark.py
scripts/print_chat.py

seems like this only works on int variables

Fix for +=

---

.github/CONTRIBUTING.md

Improved CONTRIBUTING.md

---

gpt_engineer/steps.py

Hello there👋
I have made a pull request to fix a small typo in the system messages

Fixed typo 'parallell' -> 'parallel'

---

gpt_engineer/steps.py

Hello there👋
I have made a pull request to fix a small typo in the "fix_code" function

fixed typo 'code_ouput' -> 'code_output'

---

gpt_engineer/steps.py
scripts/benchmark.py
scripts/rerun_edited_message_logs.py

before the edits, it gives me the compilation error message `TypeError: 'type' object is not subscriptable` and gives me errors when running `pre-commit run --all-files`.
after the edits, it runs perfectly and when running `pre-commit` command it works too

edit on some typing

---

scripts/print_chat.py

I refactored the loop inside the file print_chat.py for better efficiency and readability

refactor: Refactor loop for improved efficiency and readability

---

pyproject.toml
scripts/benchmark.py

- update `requires-python` to >=3.8 because `pre-commit==3.3.3` requires >=3.8 and if using a lower version installing dependencies will fail:
```
ERROR: Could not find a version that satisfies the requirement pre-commit==3.3.3 (from gpt-engineer) (from versions: 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.2.10, 0.2.11, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.6.8, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.12.2, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.15.0, 0.15.1, …
```

update pyptoject and revert suppress KeyboardInterrupt

---

gpt_engineer/collect.py
tests/test_collect.py

Addresses privacy concerns raised by https://github.com/AntonOsika/gpt-engineer/issues/415 
Data collection should never be opt-out.

changed feedback collection from opt-out to opt-in

---

gpt_engineer/preprompts/generate

this phrase was written twice "Make sure that every detail of the architecture is, in the end, implemented as code."

remove a duplicate phrase from the prompt

---

.github/workflows/codespell.yml
.pre-commit-config.yaml
benchmark/RESULTS.md
pyproject.toml

congrats on a pretty clean project! You can keep it clean with codespell now ;)

codespell: workflow, config + 1 single uno only typo fixed!

---

.pre-commit-config.yaml
README.md
tests/__init__.py

pre-commit configuration was [merged while having some formatting issues](https://github.com/AntonOsika/gpt-engineer/pull/426) and we were getting [this error](https://github.com/AntonOsika/gpt-engineer/actions/runs/5437288460/jobs/9887732141?pr=408#step:4:70)

Hotfix pre commit config

---

.gitignore
.pre-commit-config.yaml
README.md
gpt_engineer/collect.py
gpt_engineer/learning.py
gpt_engineer/main.py
pyproject.toml

Add flow to ask for consent to share learnings – finally

---

gpt_engineer/main.py

This PR fixes #315 by correcting the examples project path.

Fix examples project path in main

---

gpt_engineer/main.py

The PR that enabled .env was breaking.  See issues:  #589 
#590 
I tested this with OPENAI_API_KEY set in both .env and as a bash env variable and it worked.

Fix missing OPENAI_API_KEY

---

docker-compose.yml
docker/Dockerfile
docker/README.md

Minor Issues with the Docker Updated

Docker Update

---

README.md
gpt_engineer/ai.py

Hi @AntonOsika,
Thought I'd give the new WizardCoder models a go, they are pretty impressive!
I was going to try and run the benchmarks, but it was a bit finicky, so I did this instead :)

feat: added support for open source models, added instructions to docs

---

gpt_engineer/db.py
gpt_engineer/main.py
tests/steps/test_archive.py

Reverts AntonOsika/gpt-engineer#659

Revert "Simplify which folders are used"

---

pyproject.toml

Reverts AntonOsika/gpt-engineer#666

Revert "Bump the release version in pyproject.toml"

---

.env.template
gpt_engineer/ai.py
pyproject.toml

Reverts AntonOsika/gpt-engineer#660

Revert "add support for anthropic, azure, aleph alpha, ai21, togetherai, cohere, replicate, huggingface inference endpoints, etc. "

---

gpt_engineer/ai.py

issue #645 about double token count looks legit. This PR makes changes accordingly.

token count correction according to #645

---

README.md

Added a few lines to the README to give instructions on where to put code.  See issue #691

added instructions for how to use improve code mode

---

evals/EVAL_NEW_CODE_RESULTS.md
evals/IMPROVE_CODE_RESULTS.md
evals/eval_tools.py
evals/evals_existing_code.py
evals/evals_new_code.py

Zero temperature for more reproducibility + exposing the reporting function so that we get a report also from code gen evals.

Zero temperature code gen evals + reporting

---

README.md

As a new user, the instructions confused me.
It gave me a false sense of how gpt-engineer handles paths.
Note: this assumes that code for improvement does not have to be in the `projects/` folder, is this true?

More clear readme instructions

---

gpt_engineer/db.py
gpt_engineer/main.py
gpt_engineer/steps.py
tests/steps/test_archive.py
tests/test_collect.py
tests/test_db.py

Added new DB called `project_metadata` with the path of `.gpteng`.
Moved memory, archive, and `file_list.txt` to `.gpteng`.
issue #665

Add project_metadata as .gpteng and relocate files

---

gpt_engineer/ai.py

Uses the backoff library to "try again" if the account hits rate limit.

Handle rate limit error with backoff

---

gpt_engineer/api.py

Made a change to allow any port to be used with the agent interface and to run the interface programatically.

allows the agent interface to be run on any port

---

README.md
gpt_engineer/main.py

Added some enhancements, see the suggestions from https://github.com/AntonOsika/gpt-engineer/pull/740#pullrequestreview-1648784081

Preprompts tests and docs

---

docs/open_models.md

just a simple typo fix for the docos, link had a bad character in it.

fixed broken ref to Runpod template setup

---

.github/workflows/ci.yaml

ci: pipx install poetry, and use setup-python cache support for poetry

---

gpt_engineer/core/token_usage.py
poetry.lock

Fixes https://github.com/gpt-engineer-org/gpt-engineer/issues/921

fix: workaround for refactor on new versions of langchain

---

.gitignore

Updating .gitignore to resolve #937 bug

updating gitignore for /projects*

---

docker/Dockerfile

fix: install curl in docker image

---

docs/DOCS_BUILDING.md

docs: update DOCS_BUILDING.md

---

ROADMAP.md

Simplified the file and moved the explanatory part to the Project's readme.

Update and simplify ROADMAP.md

---

gpt_engineer/applications/cli/file_selector.py

Provide utf-8 encoding to file open command.  Previously done in https://github.com/gpt-engineer-org/gpt-engineer/pull/801 but lost in merges. 
Addresses https://github.com/gpt-engineer-org/gpt-engineer/issues/1032

Bug Fix: Unicode files

---

.github/CONTRIBUTING.md
WINDOWS_README.md
docs/introduction.md

Fixing some of the broken links in the static documentation

Fixing some of the links in the static documentation

---

gpt_engineer/core/chat_to_files.py
poetry.lock
pyproject.toml

Add timeout while searching for git diffs in LLMs response
