- .gitignore
- ai.py
- chat_to_files.py
- db.py
- main.py
- pyproject.toml
- requirements.txt
- scripts/rerun_edited_message_logs.py
- steps.py
Hi @AntonOsika 
I decided to apply a minor clean up and add a few details for the near future.
- I have pinned the requirements for now until we decide on a better approach to handle dependencies (I suggest [pip-tools](https://pip-tools.readthedocs.io/en/latest/))
- I have added a `pyproject.toml` file that contains `ruff` and `black` configurations, I believe that having these can help us maintain a cleaner codebase. (notice I have ran `black` and `ruff` on the existing codebase, no functionality has been changed)
- I have updated the `.gitignore` file, I have kept it minimal for now.
For the near future I was thinking a few tasks I can do, of course these are just suggestions, let me know your thoughts:
- write a proper `Makefile` for easier installation/run.
- setup `pip-tools`
- setup …
> Minor clean up

- ai.py
Addresses #9, #30, and #34. Simply revert model to gpt-3.5-turbo when gpt-4 is not available for the provided API key, and print out a message telling the user.
> Revert model to gpt-3.5-turbo when gpt-4 is not available.

- .github/CONTRIBUTING.md
- .gitignore
- .pre-commit-config.yaml
- README.md
- requirements.txt
Closes #57 
Please find the necessary changes to setup `pre-commit` in the project.
Also, I added the `.github/CONTRIBUTING.md` file where the installation and usage of `pre-commit` is explained in detail along side some other information regarding contributions.
> Pre commit setup

- gpt_engineer/steps.py
> improve execution step

- gpt_engineer/steps.py
The current version would execute the commands even if user typed `no`.
This pull request enhances code execution security by requiring users to explicitly type "yes" in order to execute commands from the AI response.
> SECURITY: change execute_entrypoint conditions

- gpt_engineer/chat_to_files.py
- tests/test_chat_parser.py
This fixes compatibility issues in PR [#87](https://github.com/AntonOsika/gpt-engineer/pull/87) that have arisen from recent changes to the repository.
Additionally, an improvement to the parser unit tests has been done.
The goal of the this parser is to make sense of what the LLM has provided without requiring another inference call which adds time and cost overhead. My remarks on this matter were stated in [#35](https://github.com/AntonOsika/gpt-engineer/issues/35#issuecomment-1594508297).
Further debate has been conducted in PR [#94](https://github.com/AntonOsika/gpt-engineer/pull/94)
> Improved chat parsing with no AI logic

- gpt_engineer/ai.py
- gpt_engineer/main.py
- gpt_engineer/steps.py
- scripts/benchmark.py
- scripts/clean_benchmarks.py
- tests/test_db.py
This will avoid the build to fail in existing PRs
> make pre commit pass in the whole codebase

- scripts/benchmark.py
It does not require a qualifier as it is optional. Also in the system `n_benchmarks: int | None = None` was incorrect and the debugger was saying it was a mistake. I fixed the code directory to Optional.
> Benchmark is set to work as a standalone shape

- pyproject.toml
"pre-commit: command not found" was generated upon clean codepsace; "pre-commit" was in /requirements.txt, but missing in .toml file.
**Steps to reproduce**
- create default Codespace 
- run `make install`
- See error: `pre-commit: command not found`
> fix(bug): toml misconfiguration

- gpt_engineer/ai.py
- gpt_engineer/db.py
- gpt_engineer/main.py
- scripts/benchmark.py
4 File changed with 9 Additions and 10 deletions
> Refactored by Sourcery AI 

- gpt_engineer/chat_to_files.py
- tests/test_chat_to_files.py
Fixes an issue where file names surrounded by `[]` would not be stripped out properly in creating the file name. Also added some tests.
Handles the following cases
- [code.py] => code.py
- [id].jsx => [id].jsx
Fixes #169
> Fix square bracket file name issue

- gpt_engineer/chat_to_files.py
- tests/test_chat_to_files.py
Ran through the benchmark script and discovered two cases from gpt-3.5 still wasn't handling file names properly. Added test cases and regex to fix these issues. 
Fixes #211
> Additional filename handling

- gpt_engineer/ai.py
I included **from __future__ import annotations** at the top of the **gpt_engineer/ai.py** file to enable support for python versions <3.9 when running **gpt-engineer $(project)**
> enabled compatiblilty with python versions <3.9 fixes #253

- .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
This pull request adds pull request (PR) and issue templates to improve the contribution process and communication within the project. The PR template provides a structure for clear submissions, while the issue template helps in creating well-structured reports. These templates ensure consistency, improve communication, and streamline the process.
Pull Request Template: [Link to the PR template file](https://github.com/aroramrinaal/gpt-engineer/blob/add-pr-issue-templates/.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md)
Issue Template: [Link to the issue template file](https://github.com/aroramrinaal/gpt-engineer/blob/add-pr-issue-templates/.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md)
Fixes: #84
> Add pull request and issue templates

- README.md
The README mentions checking out good first issues, but provides a link to all the issues instead of the ones labeled as 'good first issue'. This PR fixes that.
> Use 'good first issue' label in issues URL

- gpt_engineer/db.py
What do you think in clarify the error message when missing a file? I had trouble understanding what was wrong when I missed some files such as the prompt "main_prompt" or the "feedback" file. 
This commit changes the error message to help the user understand what needs to be done to execute the program correctly. 
ie. When missing the "feedback" file, the error before this commit was:
`KeyError: 'feedback'`
and now is:
`KeyError: "File 'feedback' could not be found in 'C:\\xxx\\xxxx\\gpt-engineer\\projects\\test'"`
As shows figure above:
> Clarify missing files error message.

- .gitignore
- .pre-commit-config.yaml
- pyproject.toml
- scripts/benchmark.py
This PR addresses https://github.com/AntonOsika/gpt-engineer/issues/240 by adding the benchmark report after running the evaluation step. Additionally, this report can be inserted in the `benchmark/RESULTS.md` file if needed. The insertion is a bit hacky now because it is based on certain assumptions around the results file structure. I believe there's a better way of doing it so any feedback is appreciated. 
On a more general note, I was a bit confused by the difference between the `Works` and `Perfect` criteria. The current evaluation logic leaves `Works` empty if a user replies 'yes' to `Perfect` which is a bit misleading. I think if the code works it works and ideally we would measure that using tests which is probably part of the roadmap. Anyway, please take a look and let me know …
> Add benchmark report

- Makefile
Removing repetitive command `dev-install` because it does the same as `install`. Does not matter if you run `make install` or `make dev-install`, both do the same thing.
> refactor(makefile): :recycle: remove repetitive command

- gpt_engineer/db.py
- gpt_engineer/main.py
- gpt_engineer/steps.py
- tests/steps/test_archive.py
- tests/test_collect.py
- tests/test_db.py
Remove `delete_existing` run option, instead archive memory and workspace on every run;
`archive` is a step since some flows don't generate code and therefore should not archive whatever
Relates to https://github.com/AntonOsika/gpt-engineer/issues/388
> Remove `delete_existing` option; Introduce archive

- .dockerignore
- Dockerfile
- README.md
- docker-compose.yml
- entrypoint.sh
There was a problem with the previous pull request I synced the fork and it forced the pull request to get close my bad.
The previous pull request has some issues that have been pointed out by karlderkaefer the suggested solution didn't work that well forcing the container to run using the current user id and group caused some issues with the code inside the container. But it has been fixed by forcing the owner to nobody after the code generated and most of the generated code seems to prefer Debian distro, so container is using the debian with sudo to run the generated code inside the container.
> Docker And Docker-Compose Support

- docs/usage.rst
Fixed the faulty link for Github codespaces in this [page](https://gpt-engineer.readthedocs.io/en/latest/usage.html)
> Fixed Incorrect Github codespaces link

- benchmark/RESULTS.md
**Issue Addressed**: [#596](https://github.com/AntonOsika/gpt-engineer/issues/596)
**Summary**: 
This PR provides benchmark results for the GPT3.5 with default configurations. This serves as a reference for comparing with results from TDD configurations in the future.
**Changes**:
1. Ran benchmarks on GPT3.5 (default configurations) - Note: I don't have access to GPT4.
2. Documented the results for reference.
**Next Steps**:
Running the benchmarks and checking the results is time-consuming. In a subsequent effort, I plan to run the benchmarks with TDD configurations and compare the outcomes. If someone wishes to undertake this before I get to it, we now have a reference benchmark to compare against.
> Add benchmark Results for commit 8358b60 with GPT3.5-default

- README.md
- gpt_engineer/ai.py
- gpt_engineer/learning.py
- gpt_engineer/main.py
- gpt_engineer/steps.py
Hi, I'm not sure about the long term strategy how further LLMs might be integrated into gpt-engineer, but for now, I've created an easy Azure OpenAI Service integration.
A couple of people already asked in the issues and since LangChain already supports it, it's quite easy to integrate. #325 #530 
For the future, there might be a better way to integrate various LLMs, but for now I think a simple `--azure` parameter is as easy as it gets.
In addition, I moved the check_consent higher in human_review_input so all the other questions can be skipped.
The Azure OpenAI integration has been tested and works. I couldn't test the OpenAI (default) variant though.
> Add support for Azure OpenAI Service

- README.md
- docs/index.rst
- docs/open_models.rst
Remaining changes I accidentally didn't include in #639 due to pushing to the wrong remote.
This mistake won't be repeated (ran `git remote set-url origin ...`)
> fix: fix bad merge in #639

- gpt_engineer/db.py
- gpt_engineer/file_selector.py
Used -i flag on gpt eng itself and it works well 🏃
> First boostrap commit 🚀 Improving usage of typehints.

- gpt_engineer/db.py
- gpt_engineer/main.py
- tests/steps/test_archive.py
This will let folder structure look like so:
```
- .gpt_eng
- archive
- memory
- prompt
- [all the generateed code files ("workspace") stored on the top level]
```
It will also stop archiving the workspace – think we should instead version control all the project code via git and let gpt-engineer make commits directly after it generates something.
> Simplify which folders are used

- docs/installation.rst
This documentation addition addresses issue #674. I suggest adding this as a troubleshoot entry in the documentation and not in the readme, since we want to keep the readme short. The problem is of a general nature.
> tkinter install documentation entry

- .env.template
- gpt_engineer/ai.py
- pyproject.toml
Hi @AntonOsika, 
Following up on this PR - https://github.com/AntonOsika/gpt-engineer/pull/574. 
I fixed the streaming bugs and confirmed it works with azure. 
Here is the gpt-engineer working with my deployed azure instance: 
Here is the gpt-engineer working with ai21's "j2-mid" model:
For those trying to use WizardCoder / Phind-CodeLlama, we (+ this PR) also provides support for Huggingface Inference Endpoints and Baseten. 
https://docs.litellm.ai/docs/completion/supported
If anyone's using gpt-engineer in production, and would like to split traffic between a finetuned model and gpt-4 - they can do that too: https://docs.litellm.ai/docs/tutorials/ab_test_llms
Please let me know if this PR looks good or you'd still prefer to stash it. 
Happy to make any changes / update docs, if the …
> add support for anthropic, azure, aleph alpha, ai21, togetherai, cohere, replicate, huggingface inference endpoints, etc. 

- gpt_engineer/api.py
- gpt_engineer/learning.py
- scripts/test_api.py
This PR adds support for the [Agent Protocol](https://agentprotocol.ai/).  #683 There is a file called api.py which implements the protocol and scripts/test_api.py which shows how it can be used.  
Most options are supported except improve code mode.  It is not impossible to support this mode, it will just take some additional code and documentation.
> Agent Protocol Support

- gpt_engineer/api.py
Got errors when using the API for the AutoGPT benchmarks, because the GETs dont include the additional_information property. This PR fixes that issue.
> Handle undefined additional_information in agent protocol api implementation

- gpt_engineer/ai.py
- gpt_engineer/main.py
Cost conscious users would want to monitor their api usage.
Prints the total cost at the end:
```
...
If you have time, please explain what was not working (ok to leave blank)
Total api cost: 0.30204
```
> Print total api costs

- gpt_engineer/file_selector.py
To select files for improvement faster, the inital path of the file selector should be the input path.
This is especially important if using the CLI option as the printed tree can become very large otherwise.
> file_selector path as input path

- gpt_engineer/preprompts/clarify
- gpt_engineer/steps.py
#708 and #703 
tldr: clarification flow is confusing for user and adds unnecessary information that confuses GPT.
Note: does not make the list of clarifications anymore.
I would love feedback on whether this could cause unexpected consequences.
> New clarification prompt

- gpt_engineer/main.py
Makes it clearer where we are actually running, especially if we're run without an explicit path as it defaults to `projects/example`
> Print which directory gpt-engineer is using

- docs/api_reference.rst
- gpt_engineer/main.py
- gpt_engineer/steps.py
Trying to adress parts of #708
The -l CLI flag runs gpt-engineer in lite mode.
It only includes the main prompt and the fileformat.
The idea is that it should be like normal chatGPT but without copy-paste work.
I ran a few tests, unsurprisingly it is faster and cheaper.
I also experience that the output is better.
Examples:
```
gpt-engineer txtfile -l
hello_world.txt
\```
Hello world
\```Total api cost: $  0.00438
```
```
gpt-engineer db_analytics -l 
Here is the Python script that fetches data from a Redis database and prints it in a table format using the prettytable library. 
Please note that the Python script uses the requests library to fetch data from the database, as the fetch API is not available in Python. 
Also, the Python script assumes that the Redis database returns JSON …
```
> Lite mode - run without pre prompts for execution

- gpt_engineer/main.py
Hey everyone 👋, 
thanks for the great project. I found some things that I believe can benefit the project.
I use pyenv and pyenv-virtualenv and I noticed that my pip installed gpt-engineer always tries to load the .env from its site-packages directory and searches up to the root. My project is located somewhere else, so it did not find my .env. I introduced a small change that as a fallback, if the .env file isn't found before, will attempt to find it in the current working directory. (c834e6998e4e96502e7fa3cb42d2beb04b5cf4d3 and ac4cac62dcc8ae1eb989cd648f943f831eb35e2a)
I noticed that the preprompts are part of the project itself and a change inside my venv directory would a) be overwritten by an update and b) be global. I wanted to have project specific preprompts so I implemented them. …
> Load env variable handling & Project preprompt enhancement

- sweep.yaml
This PR adds the new sandbox configs to `sweep.yaml` which runs pre-commit before every Sweep commit. 
I also added rules, which makes Sweep ensure that all newly edited functions and classes will have up-to-date docstrings.
> Added new sandbox configs to sweep.yaml

- gpt_engineer/file_selector.py
In the gpt-engineer project, a TypeError was encountered in file_selector.py when attempting to join WindowsPath objects directly. The error occurred as the code expected a string instance but received a WindowsPath instance instead. To rectify this, the line of code was updated to convert WindowsPath objects to strings before joining. This change resolves the TypeError while maintaining the original functionality of the code, ensuring that the program can handle file paths correctly across different operating systems.
> Fixing TypeError in file_selector.py

- docs/index.rst
- docs/tracing_debugging.md
An updated form of https://github.com/AntonOsika/gpt-engineer/pull/701 where the tracing/debugging how to would be placed in the `user guides`
> Add W&B tracing user guide

- gpt_engineer/core/ai.py
Fixes #754. 
From a recent Langchain update, it seems the AIMessage object has a much stricter schema which only allows `is_chunk` attributes to have a `False` value. However, in gpt_engineer, the deserialization of `clarify` logs implicitly sets `is_chunk` to `True`. 
1. Either go to Langchain (or Pydantic which they use internally for model validation of their types) and loosen their requirements for an AIMessage object model. They may or may not agree with my proposal. 
2. Make it explicit that when message objects are deserialized from the  JSON string, that their `is_chunk` attribute can never be `True`. 
I go with **Fix 2**. 
This commit deserializes and stores an intermediate list, from which we explicitly set all `is_chunk` values to `False`. Since the Langchain …
> Fix: Crashes after entering additional questions

- gpt_engineer/__init__.py
- gpt_engineer/cli/__init__.py
- gpt_engineer/core/__init__.py
- pyproject.toml
Resolves cli bug resulting from refactoring in #766.  Bug errors as follows:
```bash
ModuleNotFoundError: No module named 'gpt_engineer.cli'
```
> Bugfix - CLI - Resolves error "ModuleNotFoundError: No module named 'gpt_engineer.cli'"

- gpt_engineer/__init__.py
- gpt_engineer/cli/__init__.py
- gpt_engineer/core/__init__.py
- pyproject.toml
- tests/test_install.py
Given the bug surfaced and resolved with PR #778, added tests to cover this and related cases in the future.
Created 3 tests (and cleanup utility function) in test_install.py:
* Test that the package can be installed (locally) using `pip`
* This is done in a virtual environment
* The virtual environment persists throughout the rest of the tests
* Test that all modules can be imported
* This tests only the imports of the core modules, as imports of the CLI modules is not recommended or supported (see issue #718)
* Tests that `gpt-engineer` command can be successfully run via the CLI
* This tests the bug that was resolved in PR #778 and related bugs
After test execution, the virtual environment is removed.
I could use some guidance on how to separate this PR -- which I'm raising from the …
> Adding tests for refactored CLI

- gpt_engineer/cli/collect.py
Solution to  #773 crash bug. Addressing the issue by making sure that length is measured in bytes in utf-8 encoding.
Secondly, added additional try/except clause to make sure that, in case the truncation still fails, the program doesn't crash.
> encoding before measuring byte length + extra try clause

- pyproject.toml
This solves the AiMessageChunk problem in bug report 802 and 804
> restricting langchain version to <=0.0.312

- gpt_engineer/core/steps.py
There is a leftover call to `ai.fuser()` on the `self_heal` step that prevent using the step with error 
```
Traceback (most recent call last):
File "/usr/local/bin/gpt-engineer", line 8, in <module>
sys.exit(app())
File "/app/gpt_engineer/cli/main.py", line 186, in main
messages = step(ai, fileRepositories)
File "/app/gpt_engineer/core/steps.py", line 723, in self_heal
messages.append(ai.fuser(get_platform_info()))  # add in OS and Py version
AttributeError: 'AI' object has no attribute 'fuser'
```
fix is making the change to use `HumanMessage` function directly like on other steps
> Fix leftover ai.fuser() call on self_heal

- Makefile
Just a tiny cloc make target to easily count loc in the project. I found it useful to understand where complexity hides.
> build: added cloc Makefile target to easily count loc

- README.md
- pyproject.toml
The existing commands `gpt-engineer` and `ge` to run the tool are not very optimal. Here's why.
- `gpt-engineer` command is too cumbersome and contains a hyphen which is not very easy to type. The command is too long as well.
- `ge` command is too vague and is not very memorable and doesn't directly correlate with the name of the tool i.e. 'gpt-engineer'.
The new command suggested and implemented in this PR is `gpte`. Here's the reasoning behind this.
- Memorability and Pronunciation: The acronym `gpte` clearly stems from the initial letters of gpt-engineer, making it memorable. It's also easy to pronounce, which could make verbal communication about the tool more straightforward.
- Length and Typing Ease: `gpte` strikes a balance between being too long and too short. It avoids the …
> feat: added new gpte command for better ux

- gpt_engineer/applications/cli/cli_agent.py
- gpt_engineer/applications/cli/learning.py
- gpt_engineer/core/base_execution_env.py
- gpt_engineer/core/base_memory.py
- gpt_engineer/core/default/disk_execution_env.py
- gpt_engineer/core/default/disk_memory.py
- gpt_engineer/core/default/file_store.py
- gpt_engineer/core/default/simple_agent.py
- gpt_engineer/core/files_dict.py
Refactor: Replaced Python 3.10 style type hints with traditional Optional syntax for broader compatibility for https://github.com/AntonOsika/gpt-engineer/issues/898.
> Replace the 3.10 style type hints with the traditional style.

- gpt_engineer/core/base_execution_env.py
- gpt_engineer/core/default/disk_execution_env.py
- Replaced all instances of `tuple[type, type]` with `Tuple[type, type]`.
- Imported `Tuple` from the `typing` module wherever necessary.
> Update Type Hinting from tuple to Tuple

- .github/workflows/ci.yaml
- README.md
- pyproject.toml
As requested in https://github.com/AntonOsika/gpt-engineer/issues/898#issuecomment-1858797037
Build will fail and linters will scream until the occurrences of `type1 | type2` is replaced with `Union[type1, type2]`.
Waiting for @similato87 to make the changes requested in https://github.com/AntonOsika/gpt-engineer/issues/898#issuecomment-1858796974
> ci: use Python 3.10 in linting & testing

- README.md
"Thank you for providing such a great product. I found a typo in the doc while using it. I have confirmed that it works when using the CLI parameter --use-custom-preprompts. The basis for the correction is in the following section:
gpt_engineer/applications/cli/main.py
``` 
use_custom_preprompts: bool = typer.Option(
False,
"--use-custom-preprompts",
help="""Use your project's custom preprompts instead of the default ones.
Copies all original preprompts to the project's workspace if they don't exist there.""",
),
```
> fix CLI parameter at doc

- gpt_engineer/applications/cli/cli_agent.py
- gpt_engineer/benchmark/run.py
- gpt_engineer/benchmark/types.py
- gpt_engineer/core/default/simple_agent.py
Hi @ATheorell,
I've recently made updates to the type hints and dictionary merging methods to ensure compatibility with Python 3.8. Following our discussion, it's now an opportune moment to update the PyPI package and README file. Let's indicate that this release is the latest version supporting Python 3.8 and 3.9, ensuring our users are informed of the enhancements and compatibility.
> Updated type hints and dictionary merging for Python 3.8 compatibility.

- docker/Dockerfile
I encountered problems when running Python 3.10 following the instructions, but everything worked smoothly with Python 3.11. I recommend upgrading to this version.
> Update Python in Dockerfile. 3.10->3.11

- docker/Dockerfile
pyton3.11-slim no longer includes gcc. 
Add gcc via apt install instead of finding an alternative (possibly less slim) base Docker image
> python:3.11-slim no longer has gcc

- pyproject.toml
This fixes the docker image not having the toml dependency. Error most likely introduced here https://github.com/gpt-engineer-org/gpt-engineer/pull/937/files#diff-56bcc43fa5663093cbd7d862ed7849d2e30b13257faed00e09513d88d93d8c45R27
```Traceback (most recent call last):
File "/usr/local/bin/gpt-engineer", line 5, in <module>
from gpt_engineer.applications.cli.main import app
File "/app/gpt_engineer/applications/cli/main.py", line 40, in <module>
from gpt_engineer.applications.cli.file_selector import FileSelector
File "/app/gpt_engineer/applications/cli/file_selector.py", line 27, in <module>
import toml
ModuleNotFoundError: No module named 'toml'
```
> Adding toml as dependency

- poetry.lock
`poetry` warning `Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.`
Updated in this PR
> fix: poetry lock --no-update

- .gitignore
- docs/conf.py
This [commit](https://github.com/gpt-engineer-org/gpt-engineer/commit/e28751f7ce2c943338a460cbf91af19050629348) seems to have broken the build pipeline for the docs. The builds have been failing [for the last 6 weeks](https://readthedocs.org/projects/gpt-engineer/builds/). 
I have tested my changes locally, and I can successfully build the docs. This PR should fix this issue. I also added the docs/core folder to the .gitignore as I noticed it was generated when building the documentation locally. 
I am not entirely about how the docs are being built and deployed - is this done automatically? If so, how?
Thanks!
> Fix docs build pipeline

- poetry.lock
It seems like this PR (https://github.com/gpt-engineer-org/gpt-engineer/pull/984) forgot to update the poetry.lock file. 
I was running into the following error when running `poetry install` locally: 
```sh
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.
Because gpt-engineer depends on langchain_openai (*) which doesn't match any versions, version solving failed.
```
I fixed this by running `poetry update`. 
The docs build seems to be also failing because of this issue: https://readthedocs.org/projects/gpt-engineer/builds/23220334/
> updated poetry.lock

- gpt_engineer/applications/cli/learning.py
- tests/applications/cli/test_learning.py
This PR is about adding unit test coverage and getting myself familiar with the code. I like the concept of GPT engineer and want to contribute. 
To help speed up of development of any software, a trustworthy set of unit test will help. When those tests have a high coverage (90%+) they give confidence to the developer. 
In this PR the test coverage of the `gpt_engineer.application.cli.learning` module is increased to 93%.
> test(learning): add unit tests for learning module

- .readthedocs.yaml
This PR should fix the issue #1050. 
In 1.7, poetry install added packages to the $READTHEDOCS_VIRTUALENV_PATH venv.
In 1.8, packages are added to the underlying Python env, not in the virtualenv.
As a consequence,  the packages added this way are not seen and the build fails. 
The solution is based on [this discussion](https://github.com/python-poetry/poetry/issues/9025#issuecomment-1963073941).
> Updated the readthedocs build steps to account for Poetry 1.8 change regarding virtualenvs behaviour

- gpt_engineer/core/project_config.py
- tests/test_project_config.py
Here is an implementation of the proposed `gpt-engineer.toml` configuration file as I mentioned in the last meeting and as discussed in https://github.com/gpt-engineer-org/gpt-engineer/issues/1023
Work is needed to fully integrate/implement use of the configuration.
Comments/review welcome!
> feat: added `gpt-engineer.toml` project configuration file

- gpt_engineer/core/project_config.py
- tests/test_project_config.py
Fix after my commit right before merging #1043 broke the tests
> fix: fixed broken test for gpt-engineer.toml after renaming of config section

- gpt_engineer/applications/cli/main.py
- gpt_engineer/core/default/steps.py
- gpt_engineer/core/files_dict.py
- tests/applications/cli/test_main.py
Following the guidance provided by @ATheorell and the discussions in issue #1069, I have made the necessary updates to the text output. This includes the removal of line numbers from the print output, which aligns with the consensus for a cleaner and more user-friendly display. Additionally, I have corrected the changes validation function in `improve` function.
> 1069 automatic diff failure partly meta issue

- gpt_engineer/applications/cli/main.py
> Improve `--help` output

- gpt_engineer/applications/cli/file_selector.py
This hotfix addresses issue #1090, where files expected to be visible in the *file selection* process were missing. The issue stemmed from a recent addition to our Git filtering logic, designed to streamline file management but inadvertently excluding all files within the "projects/*" folder—a common location for users to store temporary project files.
Recognizing the need to maintain both the convenience for users storing projects in the `projects/` folder and the requirement for GPTE developers to avoid unnecessary file uploads, we introduced a specific exception within our filtering logic. This adjustment ensures the `projects/` folder remains unaffected by the filter, thus preserving file visibility.
With this change, the problem highlighted in `file_selector.toml`, where no files …
> add projects/* exception for gitignore filter

- gpt_engineer/benchmark/benchmarks/gptme/load.py
The gptme benchmarking suite uses strings for prompts which causes an error because `agent#improve` assumes it's a `Prompt` object.
> fix: incorrect prompt type breaking gptme benchmarks

- .gitignore
- gpt_engineer/benchmark/__main__.py
- gpt_engineer/benchmark/benchmarks/apps/load.py
- gpt_engineer/benchmark/benchmarks/load.py
- gpt_engineer/benchmark/benchmarks/mbpp/load.py
- gpt_engineer/benchmark/benchmarks/mbpp/problem.py
- gpt_engineer/benchmark/benchmarks/mbpp/problems.py
Solves https://github.com/gpt-engineer-org/gpt-engineer/issues/914
Run with `python3 gpt_engineer/benchmark gpt_engineer/core/default/simple_agent.py mbpp`
Here are my results running for the first 47 tasks using `gpt-4-0125-preview` model
```
--- Results ---
Total time: 465.19s
Completely correct tasks: 40/47
Total correct assertions: 123/142
Average success rate: 86.52482269503545% on 47 tasks
--- Results ---
```
> Integrate MBPP benchmarks

- .github/workflows/ci.yaml
Hey! 🙂
I've made the following changes to the workflow:
- Avoid installing packages without version
- When installing a package without a version, the latest version will always be installed, even when braking changes have been released. To avoid this causing failing pipelines a version should be specified which is known to be compatible with the code base. 
- Define permissions for workflows with external actions
-  Permissions should be used when running actions written by other developers because there may be security leaks exposed through these actions.
- Avoid running CI related actions when no source code has changed
-  Running workflows which build or test certain parts of the code base without these parts being changed is useless as nothing new will be checked or created. 
- Stop …
> Fix potential github action smells

- gpt_engineer/applications/cli/file_selector.py
- gpt_engineer/applications/cli/main.py
As discussed in #1094, extracted the linting from the file selector process to enhance modularity and align with our software design patterns. Please review the updated implementation.
> extract linting process from file_selector

- .github/CONTRIBUTING.md
- gpt_engineer/core/ai.py
This PR updates the default Azure OpenAI version to use the latest `2024-05-01-preview` per [the docs](https://learn.microsoft.com/en-us/azure/ai-services/openai/api-version-deprecation).
This is in conjunction with #1153.
> #1153 - Updating Azure default OpenAI version

- gpt_engineer/applications/cli/main.py
This PR addresses #1143 by introducing a new `--sysinfo` command-line argument to the GPT-Engineer CLI tool. The `--sysinfo` argument allows users to output detailed system information for debugging purposes. This information includes the operating system, OS version, system architecture, Python version, and installed Python packages.
- **New Functionality**:
- Added a `--sysinfo` option to the Typer CLI in `main.py`.
- Implemented `get_system_info` and `get_installed_packages` functions to gather and format system information.
- **File Modifications**:
- Updated `main.py` to include the `--sysinfo` option and corresponding logic.
To use the new `--sysinfo` feature, run the following command:
```sh
python main.py --sysinfo
```
This will display the following information:
- Operating …
> Add `--sysinfo` CLI Argument to Output System Information for Debugging

- .github/workflows/ci.yaml
- tox.ini
Python 3.11 target doesn't run in `tox`. Fixing this.
> fixing tox Python 3.11 and 3.12 issues

- .github/ISSUE_TEMPLATE/bug-report.md
- docs/installation.rst
Update the bug report issue template to ask the user to report how they installed GPT-Engineer.
* **Bug Report Template**:
- Add a new section titled "Installation Method" after the "System Information" section.
- Ask users to specify whether they installed GPT-Engineer using `pip install` or by building the repository.
* **Installation Documentation**:
- Add a note to the "Stable release" section to mention the new "Installation Method" section in the bug report template.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/gpt-engineer-org/gpt-engineer?shareId=8d0134c6-49f6-4489-9857-f983af7c21ac).
> Update bug report template to include installation method

- gpt_engineer/core/chat_to_files.py
- gpt_engineer/preprompts/file_format_diff
- gpt_engineer/preprompts/improve
- tests/core/improve_function_test_cases/zbf_yml_missing_chat
- tests/core/improve_function_test_cases/zbf_yml_missing_code
- tests/core/test_chat_to_files.py
- tests/core/test_salvage_correct_hunks.py
This PR addresses the problem outlined in issue #1197, where users encountered key errors when validating diffs. The root cause of the issue was that the Large Language Model (LLM) provided consecutive diffs for the same file, leading to conflicts.
The problem was traced back to the LLM not adhering strictly to our preprompt, resulting in multiple diffs being generated for the same file. This inconsistency led to key errors during the diff validation process, causing disruptions in the workflow.
To address this, we have implemented a more robust approach to handle consecutive diffs:
1. **Enhanced Preprompt**: We revised the preprompt to explicitly instruct the LLM to avoid generating multiple diffs for the same file. The updated preprompt now includes the following directive: "Ensure to …
> 1197 failed to update new codes from gpte

- gpt_engineer/applications/cli/cli_agent.py
- gpt_engineer/applications/cli/file_selector.py
- gpt_engineer/applications/cli/main.py
- gpt_engineer/core/chat_to_files.py
- gpt_engineer/core/default/steps.py
- gpt_engineer/tools/custom_steps.py
- gpt_engineer/tools/supported_languages.py
- tests/applications/cli/test_main.py
- tests/core/test_file_selector_enhancements.py
- Improvement mode toml filelist have to be in full-path sorted mode. 
By using large project the current listing is "mixed" and very hard to use. 
- Increasing timeout value in chat_to_files finditer. 
By using DeepSeek API with "deepseek-coder" model without this timeout increment the resolution of completion is timing out quite frequently.
- Adding "--skip-file-selection" / "-s" command line option to skip toml file selection editor in improvement mode.
By using it in complex projects and repetitive tasks the file selector popup is especially disturbing and against usabilty. 
Please consider to merge the above points as they are leading to a more smooth usability experiment.
> Usability improvements
